spring.application.name=jobtracker
spring.datasource.url=jdbc:postgresql://localhost:5432/job_tracker
spring.datasource.username=job_tracker
spring.datasource.password=job_tracker

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
